In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Input
from keras.models import Model
import h5py
import sys,pdb
import numpy as np
from sklearn.utils import shuffle
import matplotlib.pyplot as plt

############################################################
# Data: Load a subset of MNIST data
# split in into train and test
############################################################
# Load hdf5 file in 'r' mode
f = h5py.File('binary_random_sp2019.hdf5', 'r') #small dataset, assume this our full data
print('keys of the dataset: ', list(f.keys())) #useful for seeing the data set name/key
human_data = f['human'][:]
machine_data = f['machine'][:]
# print(human_data.shape, machine_data.shape)
human_label = np.ones((2400, 1))
machine_label = np.zeros((2400, 1))
human = np.concatenate((human_data, human_label), axis=1)
machine = np.concatenate((machine_data, machine_label), axis=1)
all_data = np.concatenate((machine, human), axis=0)
data = shuffle(all_data)
print(data[0:20])

split=3840
x_train = data[:split, 0:20]
x_test = data[split:, 0:20]
y_train = data[:split, 20]
y_test = data[split:, 20]
# print(x_train[0], 'x samples')
# print(y_test[0], 'y samples')

############################################################
# Define a functional API model
# Layer 1:                  20 * 20
# Activation 1:             relu
# Layer 2:                  20 * 1
# Activation 2:             sigmoid
############################################################
# This returns a tensor
inputs = Input(shape=(20,))

model = Sequential([
    Dense(20, input_shape=(20,)),
    Activation('relu'),
    Dense(1),
    Activation('sigmoid'),
])


# a layer instance is callable on a tensor, and returns a tensor
# x = Dense(32, activation='relu')(inputs)
# x = Dense(64, activation='relu')(x)
# predictions = Dense(10, activation='softmax')(x)

# This creates a model that includes
# the Input layer and three Dense layers
# model = Model(inputs=inputs, outputs=predictions)

############################################################
# Model printing
############################################################
# print(model.summary())


############################################################
# Model compilation
# Must be called before starting training
############################################################
# For a multi-class classification problem
model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

############################################################
# Model training
############################################################
# if y_train is not categorical, you may use this
# or, write your own code to convert
#one_hot_labels = keras.utils.to_categorical(labels, num_classes=10)

history = model.fit(x_train, y_train, epochs=1000, batch_size=16, validation_data=(x_test, y_test))


############################################################
# Model evaluation
############################################################
score = model.evaluate(x_test, y_test, batch_size=16)
print('Test Loss = ', score[0])
print('Test Accuracy = ', score[1])

history_dict = history.history
history_dict.keys()
#dict_keys(['val_loss', 'val_acc', 'loss', 'acc'])
epochs = range(1000)
plt.clf()
acc_values = history_dict['acc']
val_acc_values = history_dict['val_acc']

plt.plot(epochs, acc_values, 'bo', label='Training acc')
plt.plot(epochs, val_acc_values, 'r', label='Validation acc')
plt.title('Training and validation accuracy')
plt.xlabel('Epochs')
plt.ylabel('Acc')
plt.legend()
plt.show()
model.save('my_model.hdf5')

Using TensorFlow backend.


keys of the dataset:  ['human', 'machine']
[[0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 1. 0.]
 [1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 1.]
 [1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0. 1. 0. 0. 1. 1


Epoch 1/1000
  16/3840 [..............................] - ETA: 29s - loss: 0.5947 - acc: 0.5625



1344/3840 [=========>....................] - ETA: 0s - loss: 0.7070 - acc: 0.5052 

2848/3840 [=====================>........] - ETA: 0s - loss: 0.7091 - acc: 0.4909

3840/3840 [==============================] - 0s 84us/step - loss: 0.7073 - acc: 0.5023 - val_loss: 0.7170 - val_acc: 0.5062


Epoch 2/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.7304 - acc: 0.3125



1520/3840 [==========>...................] - ETA: 0s - loss: 0.7026 - acc: 0.5125



3392/3840 [=========================>....] - ETA: 0s - loss: 0.7024 - acc: 0.5100

3840/3840 [==============================] - 0s 39us/step - loss: 0.7019 - acc: 0.5073 - val_loss: 0.7120 - val_acc: 0.4990


Epoch 3/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.7231 - acc: 0.3750

1424/3840 [==========>...................] - ETA: 0s - loss: 0.7010 - acc: 0.5070

3440/3840 [=========================>....] - ETA: 0s - loss: 0.6991 - acc: 0.5064

3840/3840 [==============================] - 0s 37us/step - loss: 0.6987 - acc: 0.5042 - val_loss: 0.7083 - val_acc: 0.5052


Epoch 4/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6994 - acc: 0.4375

1680/3840 [============>.................] - ETA: 0s - loss: 0.6985 - acc: 0.5006

3600/3840 [===========================>..] - ETA: 0s - loss: 0.6962 - acc: 0.5072

3840/3840 [==============================] - 0s 37us/step - loss: 0.6964 - acc: 0.5083 - val_loss: 0.7059 - val_acc: 0.5094


Epoch 5/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6682 - acc: 0.6875

1376/3840 [=========>....................] - ETA: 0s - loss: 0.6939 - acc: 0.5153

3360/3840 [=========================>....] - ETA: 0s - loss: 0.6948 - acc: 0.5074

3840/3840 [==============================] - 0s 37us/step - loss: 0.6948 - acc: 0.5073 - val_loss: 0.7040 - val_acc: 0.5135


Epoch 6/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.7397 - acc: 0.1875

1568/3840 [===========>..................] - ETA: 0s - loss: 0.6935 - acc: 0.5096

3488/3840 [==========================>...] - ETA: 0s - loss: 0.6935 - acc: 0.5149



3840/3840 [==============================] - 0s 37us/step - loss: 0.6934 - acc: 0.5156 - val_loss: 0.7026 - val_acc: 0.5083


Epoch 7/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.7202 - acc: 0.3125

1392/3840 [=========>....................] - ETA: 0s - loss: 0.6911 - acc: 0.5165

3392/3840 [=========================>....] - ETA: 0s - loss: 0.6933 - acc: 0.5144

3840/3840 [==============================] - 0s 37us/step - loss: 0.6922 - acc: 0.5198 - val_loss: 0.7015 - val_acc: 0.5104


Epoch 8/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.7039 - acc: 0.3750

1104/3840 [=======>......................] - ETA: 0s - loss: 0.6915 - acc: 0.5226

2688/3840 [====================>.........] - ETA: 0s - loss: 0.6915 - acc: 0.5238

3840/3840 [==============================] - 0s 41us/step - loss: 0.6912 - acc: 0.5266 - val_loss: 0.7010 - val_acc: 0.5104


Epoch 9/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6641 - acc: 0.6250

1600/3840 [===========>..................] - ETA: 0s - loss: 0.6919 - acc: 0.5212

3712/3840 [============================>.] - ETA: 0s - loss: 0.6903 - acc: 0.5277



3840/3840 [==============================] - 0s 37us/step - loss: 0.6905 - acc: 0.5284 - val_loss: 0.6999 - val_acc: 0.5062


Epoch 10/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6895 - acc: 0.4375

1456/3840 [==========>...................] - ETA: 0s - loss: 0.6883 - acc: 0.5433

3328/3840 [=========================>....] - ETA: 0s - loss: 0.6892 - acc: 0.5328

3840/3840 [==============================] - 0s 37us/step - loss: 0.6898 - acc: 0.5326 - val_loss: 0.6995 - val_acc: 0.5104


Epoch 11/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.7032 - acc: 0.4375

1568/3840 [===========>..................] - ETA: 0s - loss: 0.6885 - acc: 0.5300

3584/3840 [===========================>..] - ETA: 0s - loss: 0.6892 - acc: 0.5296

3840/3840 [==============================] - 0s 37us/step - loss: 0.6891 - acc: 0.5315 - val_loss: 0.6989 - val_acc: 0.4979


Epoch 12/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6774 - acc: 0.4375

1472/3840 [==========>...................] - ETA: 0s - loss: 0.6862 - acc: 0.5455

3568/3840 [==========================>...] - ETA: 0s - loss: 0.6887 - acc: 0.5356

3840/3840 [==============================] - 0s 37us/step - loss: 0.6886 - acc: 0.5362 - val_loss: 0.6989 - val_acc: 0.5073


Epoch 13/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6901 - acc: 0.3750

1440/3840 [==========>...................] - ETA: 0s - loss: 0.6889 - acc: 0.5417

3472/3840 [==========================>...] - ETA: 0s - loss: 0.6882 - acc: 0.5423

3840/3840 [==============================] - 0s 37us/step - loss: 0.6880 - acc: 0.5396 - val_loss: 0.6985 - val_acc: 0.5021


Epoch 14/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.7371 - acc: 0.3750

1840/3840 [=============>................] - ETA: 0s - loss: 0.6886 - acc: 0.5353

3840/3840 [==============================] - 0s 33us/step - loss: 0.6875 - acc: 0.5406 - val_loss: 0.6981 - val_acc: 0.5010


Epoch 15/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6873 - acc: 0.6250

 896/3840 [======>.......................] - ETA: 0s - loss: 0.6890 - acc: 0.5368

2320/3840 [=================>............] - ETA: 0s - loss: 0.6882 - acc: 0.5237

3840/3840 [==============================] - 0s 40us/step - loss: 0.6871 - acc: 0.5391 - val_loss: 0.6978 - val_acc: 0.5010


Epoch 16/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6667 - acc: 0.6875

1760/3840 [============>.................] - ETA: 0s - loss: 0.6847 - acc: 0.5534



3760/3840 [============================>.] - ETA: 0s - loss: 0.6867 - acc: 0.5468

3840/3840 [==============================] - 0s 37us/step - loss: 0.6865 - acc: 0.5487 - val_loss: 0.6974 - val_acc: 0.4969


Epoch 17/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6769 - acc: 0.5625

1056/3840 [=======>......................] - ETA: 0s - loss: 0.6859 - acc: 0.5492

2704/3840 [====================>.........] - ETA: 0s - loss: 0.6860 - acc: 0.5466



3840/3840 [==============================] - 0s 45us/step - loss: 0.6860 - acc: 0.5495 - val_loss: 0.6976 - val_acc: 0.5031


Epoch 18/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.7100 - acc: 0.5000

1408/3840 [==========>...................] - ETA: 0s - loss: 0.6812 - acc: 0.5732

3232/3840 [========================>.....] - ETA: 0s - loss: 0.6854 - acc: 0.5526

3840/3840 [==============================] - 0s 41us/step - loss: 0.6857 - acc: 0.5505 - val_loss: 0.6972 - val_acc: 0.5042


Epoch 19/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6985 - acc: 0.5000

1552/3840 [===========>..................] - ETA: 0s - loss: 0.6865 - acc: 0.5348

3568/3840 [==========================>...] - ETA: 0s - loss: 0.6845 - acc: 0.5527

3840/3840 [==============================] - 0s 37us/step - loss: 0.6851 - acc: 0.5508 - val_loss: 0.6974 - val_acc: 0.5042


Epoch 20/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6759 - acc: 0.5625

1216/3840 [========>.....................] - ETA: 0s - loss: 0.6885 - acc: 0.5411

3040/3840 [======================>.......] - ETA: 0s - loss: 0.6841 - acc: 0.5579

3840/3840 [==============================] - 0s 41us/step - loss: 0.6847 - acc: 0.5544 - val_loss: 0.6966 - val_acc: 0.5010


Epoch 21/1000


  16/3840 [..............................] - ETA: 3s - loss: 0.6567 - acc: 0.8750

1664/3840 [============>.................] - ETA: 0s - loss: 0.6812 - acc: 0.5595

3232/3840 [========================>.....] - ETA: 0s - loss: 0.6841 - acc: 0.5535

3840/3840 [==============================] - 0s 43us/step - loss: 0.6843 - acc: 0.5555 - val_loss: 0.6964 - val_acc: 0.5031


Epoch 22/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.7150 - acc: 0.4375

1568/3840 [===========>..................] - ETA: 0s - loss: 0.6817 - acc: 0.5689

3616/3840 [===========================>..] - ETA: 0s - loss: 0.6831 - acc: 0.5595

3840/3840 [==============================] - 0s 34us/step - loss: 0.6838 - acc: 0.5555 - val_loss: 0.6961 - val_acc: 0.5010


Epoch 23/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6904 - acc: 0.3750

1312/3840 [=========>....................] - ETA: 0s - loss: 0.6886 - acc: 0.5343

3264/3840 [========================>.....] - ETA: 0s - loss: 0.6852 - acc: 0.5545

3840/3840 [==============================] - 0s 41us/step - loss: 0.6835 - acc: 0.5609 - val_loss: 0.6963 - val_acc: 0.5062


Epoch 24/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6627 - acc: 0.5625

1264/3840 [========>.....................] - ETA: 0s - loss: 0.6812 - acc: 0.5562

2816/3840 [=====================>........] - ETA: 0s - loss: 0.6812 - acc: 0.5611

3840/3840 [==============================] - 0s 45us/step - loss: 0.6829 - acc: 0.5591 - val_loss: 0.6959 - val_acc: 0.5062


Epoch 25/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6714 - acc: 0.6875

1472/3840 [==========>...................] - ETA: 0s - loss: 0.6832 - acc: 0.5618

3312/3840 [========================>.....] - ETA: 0s - loss: 0.6841 - acc: 0.5528

3840/3840 [==============================] - 0s 41us/step - loss: 0.6825 - acc: 0.5602 - val_loss: 0.6962 - val_acc: 0.5042


Epoch 26/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6720 - acc: 0.5625

1440/3840 [==========>...................] - ETA: 0s - loss: 0.6795 - acc: 0.5694

3312/3840 [========================>.....] - ETA: 0s - loss: 0.6810 - acc: 0.5667



3840/3840 [==============================] - 0s 41us/step - loss: 0.6821 - acc: 0.5646 - val_loss: 0.6961 - val_acc: 0.5094


Epoch 27/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.6776 - acc: 0.4375

1472/3840 [==========>...................] - ETA: 0s - loss: 0.6814 - acc: 0.5679

3024/3840 [======================>.......] - ETA: 0s - loss: 0.6829 - acc: 0.5638



3840/3840 [==============================] - 0s 44us/step - loss: 0.6817 - acc: 0.5661 - val_loss: 0.6955 - val_acc: 0.5135


Epoch 28/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.7106 - acc: 0.5000

1600/3840 [===========>..................] - ETA: 0s - loss: 0.6834 - acc: 0.5631

3536/3840 [==========================>...] - ETA: 0s - loss: 0.6811 - acc: 0.5676

3840/3840 [==============================] - 0s 36us/step - loss: 0.6812 - acc: 0.5672 - val_loss: 0.6954 - val_acc: 0.5135


Epoch 29/1000
  16/3840 [..............................] - ETA: 0s - loss: 0.7167 - acc: 0.3750

1328/3840 [=========>....................] - ETA: 0s - loss: 0.6821 - acc: 0.5617

KeyboardInterrupt: 

In [2]:
import h5py

f = h5py.File('my_model.hdf5', 'r')
#print('keys of the dataset: ', list(f.keys()))

model_weights = f['model_weights']
optimizer_weights = f['optimizer_weights']
#print('keys of the dataset: ', list(model_weights.keys()))
#print('keys of the dataset: ', list(optimizer_weights.keys()))

dense_1 = model_weights['dense_1']
dense = dense_1['dense_1']
#print('keys of the dataset: ', list(dense.keys()))
kernel = dense['kernel:0'][:]
print(kernel)

[[ 0.45653084 -0.7761539   0.18327531 -0.3412766  -0.7932979  -0.58839387
  -0.3544953   0.44973484  0.18820171  0.47801027 -0.97954446 -0.03249133
  -0.5637154  -0.06041251  0.14665928  0.35708785  0.44693172 -0.21116719
  -0.09181093  0.3525655 ]
 [ 0.45720354  0.20349728 -0.7357336   0.05668658  0.02299213 -0.72565633
   0.03262034  0.53927135  0.81596273  0.91972667 -0.36077836 -0.85799
  -0.63587064  0.22833744  0.6836349  -0.12936796  0.66958314  0.5779074
  -0.23456417  0.48454052]
 [-0.29766348 -0.59752274  0.10532089 -0.34225598 -1.2147249  -0.3328439
   0.12858947  0.03761876 -0.75988615  0.13158788 -0.05034357  0.31860992
   0.2961815   0.31198004 -0.18967083 -0.08016331  0.56659967  0.0347921
   0.37674466  0.07976718]
 [-0.21839418 -0.61039776 -0.9344553  -0.18079753  0.5993666  -0.472662
  -0.29658657  0.6509239  -0.3183402  -0.7917746  -0.07937215  0.13166793
   0.5234219   0.04563434  0.4684807  -0.08980497 -0.3643765   0.5374571
  -0.06264493  0.06721599]
 [-0.37438536